debugging: true
save_test_predictions: true

Saving:
  save_subgroups_plots: false
  save_discriminator_plots: false
  save_error_association_plots: false
  save_metrics_per_fold_plots: false
  save_final_test_histories_plots: false
  save_model: false

clinical_target: age
log_transform_clinical_target: false  # todo: this should be removed now, as one can just do log_{target} instead
enable_domain_discriminator: false
enable_cmmn: false

Device: cpu

HPO:
  HPOStudy:
    sampler: !HPOSampler [ TPESampler, { } ]
    direction: maximize  # todo: this must depend on the selected target
  num_trials: 200

# -----------------
# Configuration for subject splitting
# -----------------
TestSplit:
  split_percentage: 0.3
  seed: 42

# -----------------
# Training configurations
# -----------------
Scalers:  # Remember that this is whatever the SingleExperiment is working on
  target:
    kwargs: { }
    name: ZNormalisation
Training:  # Remember that this is whatever the SingleExperiment is working on
  batch_size: 16
  num_epochs: 50
  verbose: true
  verbose_variables: false
  continuous_testing: true
  metrics: regression
  prediction_activation_function: null
  main_metric: r2_score  # Don't think this is used?
Warnings:
  ignore: [ NearConstantInputWarning, ConstantInputWarning, PlotNotSavedWarning, FutureWarning ]

# -----------------
# Configurations for associating prediction errors with
# other variables  todo: should remove this, as it's old code and not actually part of the pipeline
# -----------------
PredictionErrorAssociations:
  LEMON: [ ]
  Wang: [ ]
  DortmundVital: [ ]

VariablesMetrics: null