# Configurations not related to distributions of hyperparameter optimisation

Saving:
  save_discriminator_plots: false
  save_error_association_plots: false
  save_metrics_per_fold_plots: false
  save_final_test_histories_plots: true

OcularStates: [ [ eo, ec ] ]  # [ [ eo, ec ], [ ec, eo ] ]
FrequencyBands: [ alpha, beta ]  # [ delta, theta, alpha, beta, gamma ]
# The preprocessed version must be during runtime

clinical_target: age
log_transform_clinical_target: false
deviation_method: ratio
pretext_main_metric: mse
enable_domain_discriminator: false
enable_cmmn: false

HPO:
  HPOStudy:
    sampler: !HPOSampler [ TPESampler, { } ]
    direction: minimize  # todo: this must depend on the selected target
  MultiProcessing:
    max_workers: 1
  num_trials: 5

Device: cpu

# -----------------
# Datasets
# -----------------
Datasets: &Datasets
  LEMON:
    num_subjects: 10
    num_time_steps: null
    time_series_start: null
  Wang:
    num_subjects: 10
    num_time_steps: null
    time_series_start: null

# -----------------
# Configurations for associating prediction errors with
# other variables  todo: should remove this, as it's old code and not actually part of the pipeline
# -----------------
PredictionErrorAssociations:
  LEMON: [ age, sex ]
  Wang: [ age, sex ]

VariablesMetrics:
  age: [ pearson_r, spearman_rho ]
  sex: groups_metrics

# -----------------
# Configuration for subject splitting
# -----------------
SubjectSplit:
  name: KeepDatasetOutRandomSplits
  kwargs:
    left_out_dataset: LEMON
    val_split: 0.2
    num_random_splits: 1
    seed: 42
SubGroups:
  sub_groups:
    dataset_name: !GetKeys { <<: *Datasets }
  verbose: false

MLModelSubjectSplit:
  name: RandomSplitsTV
  kwargs:
    val_split: 0.2
    num_random_splits: 10
    seed: 42

TestSplit:
  split_percentage: 0.2
  seed: 42

# -----------------
# Training configurations
# -----------------
Scalers:
  target:
    kwargs: {}
    name: ZNormalisation
Training:
  batch_size: 64
  num_epochs: 20
  verbose: true
  verbose_variables: false
  continuous_testing: true
  metrics: regression
  prediction_activation_function: null
  main_metric: mae

# -----------------
# ML model configurations
# -----------------
MLModelSettings:
  aggregation_method: mean
  evaluation_metric: mse  # todo: which should I choose?
  metrics: regression
  split_percentage: 0.2  # todo: not sure which split tbh...
  test_prediction_aggregation: mean
  test_predictions_decimals: 4
  test_scores_decimals: 4
