# Configurations not related to distributions of hyperparameter optimisation

Saving:
  save_discriminator_plots: false
  save_error_association_plots: false
  save_metrics_per_fold_plots: false
  save_final_test_histories_plots: true

OcularStates: [ [ eo, ec ] ]  # [ [ eo, ec ], [ ec, eo ] ]
FrequencyBands: [ delta, theta ]  # , alpha, beta, gamma ]
# The preprocessed version must be during runtime

clinical_target: age
log_transform_clinical_target: true
deviation_method: ratio
pretext_main_metric: mse
enable_domain_discriminator: false
enable_cmmn: false

HPO:
  HPOStudy:
    sampler: !HPOSampler [ TPESampler, { } ]
  MultiProcessing:
    max_workers: 1
  num_trials: 2

Device: cpu

# -----------------
# Datasets
# -----------------
Datasets: &Datasets
  LEMON:
    num_subjects: 20
    num_time_steps: null
    time_series_start: null
  Wang:
    num_subjects: 20
    num_time_steps: null
    time_series_start: null

# -----------------
# Configurations for associating prediction errors with
# other variables  todo: should remove this, as it's old code and not actually part of the pipeline
# -----------------
PredictionErrorAssociations:
  LEMON: [ age, sex ]
  Wang: [ age, sex ]

VariablesMetrics:
  age: [ pearson_r, spearman_rho ]
  sex: groups_metrics

# -----------------
# Configuration for subject splitting
# -----------------
SubjectSplit:
  name: KeepDatasetOutRandomSplits
  kwargs:
    left_out_dataset: Wang
    val_split: 0.2
    num_random_splits: 1
    seed: 42
SubGroups:
  sub_groups:
    dataset_name: !GetKeys { <<: *Datasets }
  verbose: true

# -----------------
# Training configurations
# -----------------
Scalers:
  target:
    kwargs: {}
    name: ZNormalisation
Training:
  batch_size: 128
  num_epochs: 50
  verbose: true
  verbose_variables: false
  continuous_testing: true
  metrics: regression
  prediction_activation_function: null
  main_metric: mae