# Configurations not related to distributions of hyperparameter optimisation

debugging: true

Saving:
  save_subgroups_plots: false
  save_discriminator_plots: false
  save_error_association_plots: false
  save_metrics_per_fold_plots: false
  save_final_test_histories_plots: true

OcularStates: [ [ eo, ec ], [ ec, eo ] ]
FrequencyBands: [ delta ]  # [ delta, theta, alpha, beta, gamma ]
# The preprocessed version must be during runtime

clinical_target: age
log_transform_clinical_target: false  # todo: this should be removed now...
deviation_method: diff
pretext_main_metric: mse
enable_domain_discriminator: false
enable_cmmn: false

HPO:
  HPOStudy:
    sampler: !HPOSampler [ TPESampler, { } ]
    direction: maximize  # todo: this must depend on the selected target
  MultiProcessing:
    max_workers: 1
  num_trials: 100

Device: cpu

# -----------------
# Datasets
# -----------------
Datasets: &Datasets
  LEMON:
    num_subjects: 40
    num_time_steps: null
    time_series_start: null
  Wang:
    num_subjects: 30
    num_time_steps: null
    time_series_start: null

# -----------------
# Configurations for associating prediction errors with
# other variables  todo: should remove this, as it's old code and not actually part of the pipeline
# -----------------
PredictionErrorAssociations:
  LEMON: [ ]
  Wang: [ ]

VariablesMetrics: null
# age: [ pearson_r, spearman_rho ]

# -----------------
# Configuration for subject splitting
# -----------------
SubjectSplit:
  name: KeepDatasetOutRandomSplits
  kwargs:
    left_out_dataset: LEMON
    val_split: 0.2
    num_random_splits: 1
    seed: 42
SubGroups:
  sub_groups:
    dataset_name: !GetKeys { <<: *Datasets }
  verbose: false

MLModelSubjectSplit:
  name: RandomSplitsTV
  kwargs:
    val_split: 0.2
    num_random_splits: 10
    seed: 42

TestSplit:
  split_percentage: 0.3
  seed: 42

# -----------------
# Training configurations
# -----------------
Scalers:
  target:
    kwargs: { }
    name: ZNormalisation
Training:
  batch_size: 64
  num_epochs: 50
  log_transform_targets: log10
  verbose: true
  verbose_variables: false
  continuous_testing: true
  metrics: regression
  prediction_activation_function: null
  main_metric: mae
Warnings:
  ignore: [ NearConstantInputWarning, ConstantInputWarning, PlotNotSavedWarning ]

# -----------------
# ML model configurations
# -----------------
MLModelSettings:
  aggregation_method: median
  evaluation_metric: r2_score  # todo: which should I choose?
  metrics: regression
  split_percentage: 0.2  # todo: not sure which split tbh...
  test_prediction_aggregation: mean
  test_predictions_decimals: 4
  test_scores_decimals: 4
