# These settings will by default by passed to all HPO experiments
debugging: false
save_test_predictions: true
raise_upon_nan_predictions: TrialPruned

enable_domain_discriminator: false
enable_cmmn: false

Device: cuda

Warnings:
  ignore: [ NearConstantInputWarning, ConstantInputWarning, FutureWarning ]

# -----------------
# What to save and what not to save
# -----------------
Saving:
  save_subgroups_plots: false
  save_discriminator_plots: false
  save_error_association_plots: false
  save_model: true  # PretrainHPO will set this to True in pretext task
  performance_score_decimals: 4

# -----------------
# HP optimisation
# -----------------
HPO:
  HPOStudy:
    sampler: TPESampler
    sampler_kwargs: { n_startup_trials: 5, multivariate: true, group: true }
    direction: UNAVAILABLE  # this will be added at runtime. Inferred from the selected downstream main metric
  num_trials: 15
  num_jobs: 1

EarlyStopping:
  patience: 10

# -----------------
# Configurations for associating prediction errors with
# other variables
# -----------------
PredictionErrorAssociations:
  LEMON: [ ]
  DortmundVital: [ ]

VariablesMetrics: null