PretextTraining:
  Augmentation:  # The augmentation to use
    - BandPass
  OcularStates:  # First element is ocular state for input (O_1), second element is ocular state for target (O_2)
    - [ EC, EO ]
    - [ EO, EC ]
    - [ EC, EO ]
    - [ EO, EC ]
    - [ EC, EC ]
    - [ EO, EO ]
  TargetFeature:
    - BandPower
DownstreamVariables:
  Miltiadous:
    - mmse
    - age
  LEMON:
    - age
  SRM:
    - age
    - ravlt_tot
  Wang:
    - sex

Datasets:
  SRM:
    num_subjects: all
    kwargs:
      session: "t1"
      derivatives: true
  Miltiadous:
    num_subjects: all
    kwargs:
      derivatives: true
  LEMON:
    num_subjects: all
    kwargs:
      derivatives: false
      interpolation_method: MNE
  Wang:
    num_subjects: all
    kwargs:
      visit: 1
      derivatives: true

# -----------------
# DL architecture related
# -----------------
