# -----------------
# Data augmentation of input data
# -----------------
# A few configurations
freq_band: &freq_band !RandomChoice [ delta, theta, alpha, beta, gamma ]
autoreject: &autoreject !RandomChoice [ true, false ]
input_length: &input_length !RandomChoice [ 5, 10, 20 ]
sfreq_multiple: &sfreq_multiple !RandomChoice [ 2, 3, 4 ]
input_ocular_state: &input_ocular_state !RandomChoice [ ec, eo ]

# Augmentations
band_pass_augmented: &band_pass_augmented !StrFormat
  string: "preprocessed_band_pass_{ocular_state}/data--band_pass-{freq_band}--input_length-{input_length}s--autoreject-{autoreject}\
    --sfreq-{sfreq_multiple}fmax"
  kwargs:
    freq_band: *freq_band
    autoreject: *autoreject
    input_length: *input_length
    sfreq_multiple: *sfreq_multiple
    ocular_state: *input_ocular_state

# The selected preprocessed version
preprocessed_version: &preprocessed_version !RandomChoice
  - *band_pass_augmented

# -----------------
# Selecting target
# -----------------
# Configurations
target_freq_band: &target_freq_band !RandomChoice [ delta, theta, alpha, beta, gamma ]
target_ocular_state: &target_ocular_state !RandomChoice [ ec, eo ]

# Targets
band_power: &band_power !StrFormat
  string: "band_power_{target_freq_band}_{target_ocular_state}"
  kwargs:
    target_freq_band: *target_freq_band
    target_ocular_state: *target_ocular_state

# The selected target
target: &target !RandomChoice
  - *band_power

# -----------------
# Datasets
# -----------------
AllDatasets: &AllDatasets
  SRM:
    num_subjects: 111
    num_time_steps: null
    pre_processed_version: *preprocessed_version
    time_series_start: null
  LEMON:
    num_subjects: 203
    num_time_steps: null
    pre_processed_version: *preprocessed_version
    time_series_start: null
  #Miltiadous:
  #  num_subjects: 88
  #  num_time_steps: null
  #  pre_processed_version: *preprocessed_version
  #  time_series_start: null
  #TDBRAIN:
  #  num_subjects: 1273
  #  num_time_steps: null
  #  pre_processed_version: *preprocessed_version
  #  time_series_start: null
  Wang:
    num_subjects: 60
    num_time_steps: null
    pre_processed_version: *preprocessed_version
    time_series_start: null

OcularStateAvailability: &OcularStateAvailability
  ec: [ SRM, LEMON, Wang ]  # Miltiadous, TDBRAIN
  eo: [ LEMON, Wang ]  # TDBRAIN

InputDatasets: &InputDatasets !SelectFromDict
  - <<: *OcularStateAvailability
  - *input_ocular_state

TargetDatasets: &TargetDatasets !SelectFromDict
  - <<: *OcularStateAvailability
  - *target_ocular_state

DatasetsNames: &DatasetsNames !ListIntersection [ *InputDatasets, *TargetDatasets ]

Datasets: &Datasets !MultiSelectFromDict
  - <<: *AllDatasets
  - *DatasetsNames

# -----------------
# Configurations for associating prediction errors with
# other variables
# -----------------
PredictionErrorAssociations: !MultiSelectFromDict
  - Miltiadous: [ mmse, age, sex, clinical_status ]
    LEMON: [ age, sex ]
    SRM: [ age, ravlt_tot, sex ]
    Wang: [ age, sex ]
    TDBRAIN: [ age, sex , indication, formal_status ]
  - *DatasetsNames

VariablesMetrics:
  age: [ pearson_r, spearman_rho ]
  mmse: [ pearson_r, spearman_rho ]
  ravlt_tot: [ pearson_r, spearman_rho ]
  clinical_status: groups_metrics
  sex: groups_metrics
  indication: groups_metrics
  formal_status: groups_metrics


# -----------------
# Configuration for subject splitting (related to the cross validation)
# -----------------
SubjectSplit:
  kwargs:
    seed: 42
  name: SplitOnDataset
SubGroups:
  sub_groups:
    dataset_name: *DatasetsNames
  verbose: true

# -----------------
# Domain discriminator
# -----------------
# Using an FC module
ExponentialDecayFC: &ExponentialDecayFC
  proposed_depth: !UniformInt [ 0, 5 ]
  first_layer_multiple: !Uniform [ 0.5, 2 ]
  exponential_decrease: !RandomChoice [ 2, 3 ]
  in_features: UNDETERMINED  # Need to 'ask' the DL architecture
  num_classes: !Sum [ !MappingLength [ *Datasets ], -1 ]
  activation_function: !RandomChoice
    - name: relu
      kwargs: {}
    - name: elu
      kwargs: {alpha: !Uniform [ 0.2, 1.8 ]}

FCModule: &FCModule !RandomChoice
  - method: exponential_decay
    kwargs: *ExponentialDecayFC

# Selecting domain discriminator
DomainDiscriminator:
  discriminator: &discriminator !RandomChoice
    #- null
    - name: FCModule
      kwargs: *FCModule
  training:
    Loss:
      loss: CrossEntropyLoss
      loss_kwargs:
        reduction: mean
      weighter: null
      weighter_kwargs: { }
    metrics: !Tuple [ acc, ce_loss ]
    lambda: !LogUniform [10, -6, -1]

# -----------------
# Training configurations
# -----------------
#training_method_condition: &_training_method_condition !IsNone *discriminator
Scalers:
  target:
    kwargs: {}
    name: ZNormalisation
Training:
  batch_size: 128
  num_epochs: 50
  verbose: true
  verbose_variables: false
  continuous_testing: true
  metrics: regression
  method: !IfIsNoneElse {condition: *discriminator, true: downstream_training, false: domain_discriminator_training}
  prediction_activation_function: null
  main_metric: pearson_r  # todo: this should not be required
  learning_rate: !LogUniform [10, -5, -3]
  beta_1: !Uniform [0.8, 1.0]
  beta_2: !Uniform [0.9, 1.0]
  eps: !LogUniform [10, -10, -6]
  ValSplit:  # todo: a little weird to have it in Training config?
    name: DatasetBalancedTrainValSplit
    kwargs:
      val_split: 0.2
  target: *target
  Loss:
    loss: !RandomChoice [ MSELoss, L1Loss ]
    loss_kwargs:
      reduction: UNDETERMINED
    weighter: !RandomChoice [ null, SamplePowerWeighter ]
    weighter_kwargs:
      weight_power: !Uniform [0, 1]

# -----------------
# DL architectures
# -----------------
num_time_steps: &num_time_steps !SelectFromDict
  - delta: !MultiplierInt [ *input_length, *sfreq_multiple, 4 ]
    theta: !MultiplierInt [ *input_length, *sfreq_multiple, 8 ]
    alpha: !MultiplierInt [ *input_length, *sfreq_multiple, 12 ]
    beta: !MultiplierInt [ *input_length, *sfreq_multiple, 30 ]
    gamma: !MultiplierInt [ *input_length, *sfreq_multiple, 45 ]
  - *freq_band

# Inception network
InceptionNetwork: &InceptionNetwork
  num_classes: 1
  cnn_units: !LogUniformInt [2, 3, 6]
  depth: !NLogUniformInt [3, 3, 0, 3]

# ShallowFBCSPNet
_n_filters: &_n_filters !UniformInt [30, 51]
ShallowFBCSPNetMTS: &ShallowFBCSPNetMTS
  num_classes: 1
  num_time_steps: *num_time_steps
  n_filters_time: *_n_filters
  n_filters_spat: *_n_filters
  filter_time_length: !UniformInt [15, 36]
  pool_time_stride: &pool_time_stride !UniformInt [10, 21]
  pool_time_length: !MultiplierInt [ 5, *pool_time_stride ]
  drop_prob: !Uniform [0, 0.5]

# Deep4Net
_n_first_filters: &_n_first_filters !UniformInt [15, 36]
_filter_length: &_filter_length !UniformInt [5, 16]
Deep4NetMTS: &Deep4NetMTS
  num_classes: 1
  num_time_steps: *num_time_steps
  n_filters_time: *_n_first_filters
  n_filters_spat: *_n_first_filters
  n_filters_2: !MultiplierInt [ 2, *_n_first_filters ]
  n_filters_3: !MultiplierInt [ 4, *_n_first_filters ]
  n_filters_4: !MultiplierInt [ 8, *_n_first_filters ]
  filter_time_length: *_filter_length
  filter_length_2: *_filter_length
  filter_length_3: *_filter_length
  filter_length_4: *_filter_length
  drop_prob : !Uniform [0, 0.5]

# Selected DL architecture
DLArchitecture: !RandomChoice
  - model: InceptionNetwork
    kwargs: *InceptionNetwork
  - model: ShallowFBCSPNetMTS
    kwargs: *ShallowFBCSPNetMTS
  - model: Deep4NetMTS
    kwargs: *Deep4NetMTS

# -----------------
# Varied numbers of channels
# -----------------
Varied Numbers of Channels:
  kwargs:
    RBPDesigns:
      RBPDesign0:
        cmmn_kwargs: null
        num_designs: 1
        pooling_methods: MultiMSSharedRocketHeadRegion
        pooling_methods_kwargs:
          bias: false
          latent_search_features: 23
          max_receptive_field: 141
          num_kernels: 321
          share_search_receiver_modules: true
        pooling_type: multi_cs
        split_methods:
        - CentroidPolygons
        - CentroidPolygons
        - CentroidPolygons
        - CentroidPolygons
        split_methods_kwargs:
        - channel_positions: &id001
          - Miltiadous
          k: &id002
          - 4
          - 3
          - 2
          - 3
          - 4
          - 3
          - 2
          - 3
          - 4
          min_nodes: 4
        - channel_positions: *id001
          k:
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          - 2
          min_nodes: 3
        - channel_positions: *id001
          k: *id002
          min_nodes: 1
        - channel_positions: *id001
          k: *id002
          min_nodes: 1
        use_cmmn_layer: false
    normalise_region_representations: true
  name: RegionBasedPooling
