MLFeatureExtraction:
  features: [ log10_band_power_delta_eo, log10_band_power_theta_eo, log10_band_power_alpha_eo, log10_band_power_beta_eo,
              log10_band_power_gamma_eo ]
PredictionModelsHPO: { in_freq_band: all }
PretrainHPO:
  in_ocular_state: ec  # It is possible to make these HPs, but we would lose the connection to reactivity I think
  out_ocular_state: eo
  in_freq_band: all
  save_ssl_biomarkers: true
SimpleElecsslHPO:
  deviation_method: &deviation_method diff
  num_additional_trials: 10
  in_ocular_state: ec
  out_ocular_state: eo
  include_pseudo_targets: true
MultivariableElecsslHPO:
  IOSpaces: # In ocular state, out ocular state, in frequency band, out frequency band
    - [ [ ec, eo ], [ all, delta ] ]
    - [ [ ec, eo ], [ all, theta ] ]
    - [ [ ec, eo ], [ all, alpha ] ]
    - [ [ ec, eo ], [ all, beta ] ]
    - [ [ ec, eo ], [ all, gamma ] ]
  deviation_method: *deviation_method
  num_random_reuse: 500
  num_additional_trials: 5
  include_pseudo_targets: true